Kavya SampathKumar -                      NUMPY AND PANDA Assignment

1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
import numpy as np

In [ ]:
temperatures_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2. Inspection and Properties:
● Inspect the shape, data type, and the number of elements in the array. Inspect the shape of the temperatures_w1 array.

In [ ]:
type(temperatures_w1)

numpy.ndarray

In [ ]:
shape=temperatures_w1.shape
print(shape)

(7,)


In [ ]:
size=temperatures_w1.size
print(size)

7


3. Array Operations:
● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
for cel in temperatures_w1:
    far=(cel*9/5)+32
    print(far)

72.5
77.54
69.44
74.12
78.98
76.64
71.42


In [ ]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
max(temperatures_w1)

np.float64(26.1)

In [ ]:
min(temperatures_w1)

np.float64(20.8)

In [ ]:
temperatures_w1.mean()

np.float64(23.542857142857144)

4. Array Slicing and Indexing:
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [ ]:
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
first_three_days=temperatures_w1[0:3]
print(first_three_days)

[22.5 25.3 20.8]


In [ ]:
last_two_days=temperatures_w1[-2:]
print(last_two_days)

[24.8 21.9]


In [ ]:
len(temperatures_w1)

7

In [ ]:
mid_3_days=temperatures_w1[2:5]
print(mid_3_days)

[20.8 23.4 26.1]


5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [ ]:
temperatures=np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],[19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6. Inspect and Slice the 2D Array:
● Inspect and print the shape, data type, and total number of elements in the temperatures array.
● Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [ ]:
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
type(temperatures)

numpy.ndarray

In [ ]:
shapes=temperatures.shape
print(shapes)


(2, 7)


In [ ]:
sizes=temperatures.size
print(sizes)

14


In [ ]:
W1_temp=temperatures[0]
print(W1_temp)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
W2_temp=temperatures[1]
print(W2_temp)

[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
W1_last_2days=W1_temp[-2:]
print(W1_last_2days)

[24.8 21.9]


In [ ]:
W2_last_2days=W2_temp[-2:]
print(W2_last_2days)

[22.8 20.1]


1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [ ]:
import pandas as pd

In [ ]:
Marks=[95,92,89,85,80]
S=pd.Series(Marks)
print(S)

0    95
1    92
2    89
3    85
4    80
dtype: int64


In [ ]:
datatype=S.dtype
print(datatype)

int64


In [ ]:
print(S)

0    95
1    92
2    89
3    85
4    80
dtype: int64


In [ ]:
S=pd.Series(Marks,index=[ 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(S)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.
● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
● Use the iloc accessor to retrieve the mark of the 3rd rank student.
● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [ ]:
print(S)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
FirstRank=S.iloc[0] #S.["Rank1"] also give same answer
print(FirstRank)

95


In [ ]:
Top_3_Ranks=S.loc[["Rank1","Rank2","Rank3"]]
print(Top_3_Ranks)

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
ThirdRank=S.iloc[2]
print(ThirdRank)

89


In [ ]:
marks_greater_than_90 = S[S > 90]
print(marks_greater_than_90)

Rank1    95
Rank2    92
dtype: int64


In [ ]:
print(marks_greater_than_90)

Rank1    95
Rank2    92
dtype: int64


In [ ]:
d=marks_greater_than_90.dtype
print(d)

int64


In [ ]:
information=marks_greater_than_90.info
print(information)

<bound method Series.info of Rank1    95
Rank2    92
dtype: int64>


3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.
● Remove the entry corresponding to the last rank from the Series.
● Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
print(S)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
S["Rank1"]=100
print(S)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
R=S.drop("Rank5")
print(R)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
for m in S:
  Cgpa = m/10
  cgpa=pd.Series()
  print(Cgpa)
  m=m+1

10.0
9.2
8.9
8.5
8.0


1. Creating Pandas DataFrame:
● Create a Pandas DataFrame named transactions with the following data:
➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [ ]:
transactions = pd.DataFrame({
'TransactionID':[101,102,103,104,105,106,107,108,109,110],
'ProductCategory':['Electronics','Clothing','Electronics','Furniture','Clothing','Electronics','Furniture','Clothing','Furniture','Electronics'],
'Region':['North','South','North','East','West','North','East','West','South','North'],
'Amount':[200,150,300,450,200,250,300,180,350,400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:
● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
● Display only the 'ProductCategory' and 'Amount' columns.
● Retrieve the last 3 columns of the DataFrame using iloc or loc.
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
● Find the value counts for the 'ProductCategory' column.
● Find the unique values in the 'Region' column.
● Group by 'Region' and find the mean amount for each region.

In [ ]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [ ]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


In [ ]:
transactions.shape

(10, 4)

In [ ]:
transactions.dtypes

,0
TransactionID,int64
ProductCategory,object
Region,object
Amount,int64


In [ ]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
two_columns=transactions[["ProductCategory","Amount"]]
print(two_columns)

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
last=transactions.loc[:, ['ProductCategory','Region', 'Amount']]
print(last)

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
Filter_rows=transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(Filter_rows)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
transactions['ProductCategory'].value_counts()

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


In [ ]:
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
transactions.groupby('Region')['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
● Remove the row with TransactionID 109.
● Delete the 'Discount' column from the DataFrame.

In [ ]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions.drop("Discount",axis=1,inplace=True)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
